### ISSUE TITLE
Atualização do README.md, referência acriar issue com marcadores

### ISSUE THREAD

**Issue by fititnt** [braziljs/conf-suggestions#13]
> Crie uma issue com a label `conf-content` e descreva qual o conteúdo você gostaria de ver em próximas edições da BrazilJS Conf.
> 
> Crie uma issue com a label `conf-speaker` e descreva qual palestrante você gostaria de ver em próximas edições da BrazilJS Conf. Descreva o motivo de você estar sugerindo o palestrante, com links, etc.
> 
> Crie uma issue com a label `conf-sponsor` e descreva qual empresa você gostaria de ver em próximas edições da BrazilJS Conf. Descreva o motivo de você estar sugerindo a empresa, com links, etc.
> 
> Crie uma issue com a label `conf-other` e descreva a sua sugestão para próximas edições da BrazilJS Conf.

Nesse momento, o [REAME.md](../blob/master/README.md) diz que pessoas todas as pessoas devem criar um tópico já com o marcador, porém as únicas pessoas que podem fazer isso são duas os dois admins do repositório.

O ideal seria trocar isso, e apenas informar que a tag tal reune o assunto, sem induzir a pessoa a criar algo que ela não pode.

**Comment by jaydson** [comment]
Boa @fititnt , achei q todos poderiam escolher a label. Vou mudar isso.
Valeu! :+1:

**Comment by jaydson** [comment]
Done https://github.com/braziljs/conf-suggestions/blob/master/README.md
