### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by dannluciano** [braziljs/conf-suggestions#28]
Descrição: Galera gostaria muito de ver uma palestra sobre WebAssembly.
Acredito que nenhuma tecnologia web vai ser tão transformadora como ela.
Link: http://webassembly.org/

**Comment by viniciusCamargo** [comment]
Concordo totalmente!!! WebAssembly is a must :P

Um cara massa pra falar sobre isso seria o [Axel Rauschmayer](https://twitter.com/rauschma). Além de manjar muito de JS eu já vi ele twitando sobre wasm. Ele também tem um post bem esclarecedor sobre o assunto:  http://www.2ality.com/2015/06/web-assembly.html

**Comment by jaydson** [comment]
O Axel já foi indicado aqui #7 :)
Vamos tentar.
