### ISSUE TITLE
Guarda volumes

### ISSUE THREAD

**Issue by ftonato** [braziljs/conf-suggestions#40]
**Descrição:** Gostaria que a BrazilJS Conf tivesse um espaço para guarda volumes dos participantes.
**Link:** [Significado/definição de guarda-volumes](https://www.priberam.pt/dlpo/guarda-volumes)  
[Imagem de um guarda-volumes](https://media-cdn.tripadvisor.com/media/photo-s/06/3c/3b/6d/biblioteca-parque-estadual.jpg)  

Os convidados/participantes poderiam guardar algumas coisas como bolsas, mochilas, roupas (casacos), lanches, brindes, computadores, entre outros itens que preferissem.

Isso ajudaria, principalmente, a melhorar o fluxo das pessoas na hora em que estão no coffee break.

**Comment by manobi** [comment]
Esse ano vai rolar isso?

**Comment by ftonato** [comment]
@manobi no :(

**Comment by felipenmoura** [comment]
infelizmente não, mas a sugestão é muito válida e já demos uma olhada em como fazer isso para o próximo ano.
O próprio Shopping Barra tem um guarda volume deles, mas não sei dizer o tamanho do que cabe lá.
O problema do guarda volumes é uma parte burocrática requerida, com seguro, responsabilidade, etc.

Mas vamos levantar as possibilidades para o próximo ano :)

**Comment by ftonato** [comment]
Estou encerrando issues e pull-requests desatualizados que não são mais relevantes, considerando quanto tempo se passou desde que foram abertos.
