### ISSUE TITLE
CouchDB / PouchDB

### ISSUE THREAD

**Issue by glaucocustodio** [braziljs/conf-suggestions#6]
CouchDB: banco de dados NoSQL com API HTTP. A versão 2 (atualmente em RC) conta com uma poderosa API para queries inspirada no MongoDB (https://github.com/apache/couchdb-mango)
Link: https://couchdb.apache.org/

PouchDB: banco de dados inspirado pelo CouchDB designado para rodar no browser.
Link: https://pouchdb.com/

Usando essas tecnologias podemos construir aplicações web/mobile sincronizadas com servidor remoto sem ter de construir nossa própria API.

**Comment by marcelaraujo** [comment]
PouchDB 👍 
CouchDB 👎

**Comment by fititnt** [comment]
@glaucocustodio fecha você mesmo esse issue e cria dois diferentes. O próprio @marcelaraujo já deu um exemplo de porque dois ao mesmo tempo vai dar confusão.

**Comment by jaydson** [comment]
Boa ideia @fititnt !
Pode fazer isso @glaucocustodio ?
